# Generated by Django 4.2.30 on 2026-05-14 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_mac', models.CharField(help_text='MAC Address o ID único', max_length=50, unique=True)),
                ('nombre_alias', models.CharField(blank=True, help_text=' Estaca Secador 1', max_length=100)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_instalacion', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(help_text='Ej: LOTE-001-Pergamino', max_length=50, unique=True)),
                ('variedad', models.CharField(help_text='Pergamino Lavado', max_length=100)),
                ('peso_inicial_qq', models.DecimalField(decimal_places=2, help_text='Peso en quintales (qq)', max_digits=8)),
                ('precio_mercado_actual', models.DecimalField(decimal_places=2, help_text='Precio por qq en USD', max_digits=8)),
                ('esta_activo', models.BooleanField(default=True, help_text='¿Sigue secándose en la finca?')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Lote de Café',
                'verbose_name_plural': 'Lotes de Café',
            },
        ),
        migrations.CreateModel(
            name='LecturaSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('temp_ambiente', models.DecimalField(decimal_places=2, help_text='Ta en °C', max_digits=5)),
                ('humedad_relativa', models.DecimalField(decimal_places=2, help_text='HR en %', max_digits=5)),
                ('presion_atmosferica', models.DecimalField(blank=True, decimal_places=2, help_text='P en hPa', max_digits=7, null=True)),
                ('punto_rocio', models.DecimalField(blank=True, decimal_places=2, help_text='Tr en °C', max_digits=5, null=True)),
                ('radiacion_solar', models.DecimalField(blank=True, decimal_places=2, help_text='W/m2', max_digits=6, null=True)),
                ('lluvia', models.BooleanField(default=False)),
                ('temp_grano', models.DecimalField(decimal_places=2, help_text='Tc en °C', max_digits=5)),
                ('humedad_estimada', models.DecimalField(decimal_places=2, help_text='HE en %', max_digits=5)),
                ('voltaje_bateria', models.DecimalField(decimal_places=2, help_text='V', max_digits=4)),
                ('rssi', models.IntegerField(help_text='Fuerza de la señal ', null=True)),
                ('es_valida', models.BooleanField(default=True)),
                ('codigo_error', models.CharField(blank=True, max_length=20, null=True)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='core.dispositivo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas', to='core.lote')),
            ],
            options={
                'verbose_name': 'Lectura de Sensor',
                'ordering': ['-fecha_hora'],
                'get_latest_by': 'fecha_hora',
            },
        ),
    ]
